import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { exec, gateEnv } from "./gate.mjs";
import { detectEnvFailure } from "./envfail.mjs";
import { norm } from "./paths.mjs";

/**
 * Pre-run checks on the frozen tests themselves.
 *
 * Once a cheaper model writes the tests, the tests stop being trustworthy by
 * construction and have to be *verified*. Two of the three checks Opus did by
 * hand in run 1 are purely mechanical and belong here — no model calls, no
 * network, no cost:
 *
 *   1. every test file parses
 *   2. every test FAILS against an auto-generated null stub
 *
 * The third — that a plausible-wrong implementation is caught — needs a real
 * implementation to mutate, so it runs after the node passes. See mutate.mjs.
 */

/**
 * The languages the stub check actually understands.
 *
 * Everything below — `node --check`, the ESM import parser, the Proxy stub — is
 * JavaScript. Run against a Python or Go test this produced a `syntax` finding
 * on every node and killed the command, while the docs described non-vacuity as
 * a general guarantee. Neither the failure nor the guarantee was honest.
 *
 * So the scope is named. A test file in another language is reported as
 * unchecked rather than as broken, and `ok` does not depend on it — the same
 * treatment `no-tests` already gets. Better to say "this was not verified" than
 * to say "verified" when nothing was.
 */
export const CHECKABLE_EXT = new Set([".mjs", ".js", ".cjs", ".jsx", ".ts", ".tsx", ".mts", ".cts"]);

export function isCheckable(rel) {
  return CHECKABLE_EXT.has(path.extname(String(rel)).toLowerCase());
}

const IMPORT_RE =
  /import\s+(?:([\w$]+)\s*,\s*)?(?:\{([^}]*)\}|\*\s+as\s+([\w$]+)|([\w$]+))?\s*from\s*['"]([^'"]+)['"]/g;

/** Names a test file imports from a given module path. */
export function importedNames(testSource, testFilePath, targetRel, root) {
  const names = new Set();
  let ns = false;
  let m;
  IMPORT_RE.lastIndex = 0;
  while ((m = IMPORT_RE.exec(testSource))) {
    const [, defaultWithBraces, braced, star, bare, spec] = m;
    if (!spec.startsWith(".")) continue;
    const resolved = norm(path.relative(root, path.resolve(path.dirname(testFilePath), spec)));
    if (resolved !== norm(targetRel)) continue;
    if (star) ns = true;
    if (bare || defaultWithBraces) names.add("__default__");
    for (const part of (braced || "").split(",")) {
      const t = part.trim();
      if (!t) continue;
      const as = t.split(/\s+as\s+/);
      names.add(as[0].trim());
    }
  }
  return { names: [...names], namespace: ns };
}

/**
 * A stub that imports cleanly and does nothing useful. Importable matters: a
 * module-not-found error would prove only that the file is absent, not that the
 * tests discriminate.
 */
export function buildStub(names) {
  // Each export must survive being used as a function, an object, an array, or a
  // primitive without throwing — otherwise the test dies on a TypeError and we
  // learn nothing about whether it actually asserts anything. A callable Proxy
  // absorbs every access shape and yields null.
  const lines = [
    "// Auto-generated by `trellis verify-tests`. Never written to your repo.",
    "// Every export is inert. A gate that passes against this file asserts nothing.",
    "",
    "const inert = () => new Proxy(function () {}, {",
    "  apply: () => null,",
    "  construct: () => ({}),",
    "  get(_t, p) {",
    "    if (p === Symbol.toPrimitive) return () => null;",
    "    if (p === Symbol.iterator) return function* () {};",
    "    if (p === Symbol.toStringTag) return 'Inert';",
    "    if (p === 'length' || p === 'size') return 0;",
    "    if (p === 'then' || p === 'constructor') return undefined;",
    "    return undefined;",
    "  },",
    "  has: () => false,",
    "  ownKeys: () => [],",
    "  getOwnPropertyDescriptor: () => undefined,",
    "});",
    "",
  ];
  for (const n of names) {
    if (n === "__default__") continue;
    lines.push(`export const ${n} = inert();`);
  }
  if (names.includes("__default__")) lines.push(`export default inert();`);
  if (!names.length) lines.push("export {};");
  return lines.join("\n") + "\n";
}

/**
 * Run the mechanical checks. Returns { ok, findings: [{ nodeId, kind, message }] }.
 * Never touches the repo — everything happens in a temp copy.
 */
export async function verifyTests(cfg, graph, nodes, root, { log = () => {} } = {}) {
  const findings = [];

  for (const node of nodes.values()) {
    const tests = node.tests || [];
    if (!tests.length) {
      findings.push({ nodeId: node.id, kind: "no-tests", message: "declares no frozen tests; nothing pins its behaviour" });
      continue;
    }

    // Existence is language-independent and is checked for every test.
    let syntaxOk = true;
    for (const t of tests) {
      if (!fs.existsSync(path.join(root, t))) {
        findings.push({ nodeId: node.id, kind: "missing-test", message: `${t} does not exist` });
        syntaxOk = false;
      }
    }
    if (!syntaxOk) continue;

    // Everything past here is JavaScript-specific. Say so rather than emitting a
    // parse error for every Python file and calling the node broken.
    const foreign = tests.filter((t) => !isCheckable(t));
    if (foreign.length) {
      findings.push({
        nodeId: node.id,
        kind: "unsupported-language",
        message:
          `${foreign.join(", ")} — verify-tests checks JavaScript and TypeScript only, so ` +
          `non-vacuity was NOT established for this node. Its gate still runs during \`run\`; ` +
          `what is missing is the proof that the test rejects a do-nothing implementation.`,
      });
      continue;
    }

    // ---- 1. syntax ----
    for (const t of tests) {
      const abs = path.join(root, t);
      const r = await exec(`node --check "${abs}"`, root, 30000);
      if (r.code !== 0) {
        findings.push({ nodeId: node.id, kind: "syntax", message: `${t} does not parse:\n${String(r.output).slice(0, 500)}` });
        syntaxOk = false;
      }
    }
    if (!syntaxOk) continue;

    // ---- 2. non-vacuity against a null stub ----
    const scratch = fs.mkdtempSync(path.join(os.tmpdir(), `trellis-verify-${node.id}-`));
    try {
      copyRepo(root, scratch, cfg);

      const targets = (node.write || []).filter((w) => !w.includes("*") && /\.(mjs|js|cjs|ts)$/.test(w));
      if (!targets.length) {
        findings.push({ nodeId: node.id, kind: "unstubbable", message: `write scope has no concrete module path, so non-vacuity cannot be checked` });
        continue;
      }

      for (const target of targets) {
        const names = new Set();
        let ns = false;
        for (const t of tests) {
          const src = fs.readFileSync(path.join(root, t), "utf8");
          const got = importedNames(src, path.join(root, t), target, root);
          got.names.forEach((n) => names.add(n));
          ns ||= got.namespace;
        }
        if (!names.size && !ns) continue; // this test file doesn't import this target
        const abs = path.join(scratch, target);
        fs.mkdirSync(path.dirname(abs), { recursive: true });
        fs.writeFileSync(abs, buildStub([...names]));
      }

      const r = await exec(node.gate, scratch, cfg.gate.timeoutMs, gateEnv(cfg));
      if (r.code === 0) {
        findings.push({
          nodeId: node.id,
          kind: "vacuous",
          message:
            `the gate PASSES against a stub whose exports all return null. ` +
            `These tests assert nothing a worker must actually satisfy — a node with ` +
            `vacuous tests will go green without working.`,
        });
      } else {
        // A non-zero exit is the signal that the test has teeth — but a missing
        // dependency exits non-zero too, which would make every test in a broken
        // environment look strong and green-light a run that then fails on every
        // node. This is the cheapest place in the whole system to catch that: the
        // gates all run here, before any worker and before any money is spent.
        const env = detectEnvFailure(r.output);
        if (env) {
          findings.push({
            nodeId: node.id,
            kind: "env-failure",
            message:
              `the gate failed for an environment reason, not a test reason: ${env.hint}.\n` +
              `Non-vacuity could NOT be established — a missing dependency makes every ` +
              `test look strong. Install it and re-run verify-tests before running.`,
          });
        } else {
          log(node.id, "non-vacuous");
        }
      }
    } finally {
      fs.rmSync(scratch, { recursive: true, force: true });
    }
  }

  // `ok` means "nothing was found that makes a test untrustworthy". A node whose
  // language this cannot check has not been shown to be untrustworthy, only
  // unverified — the same standing as no-tests. Callers that need to know how
  // much was actually proven read SOFT_FINDINGS out of `findings`.
  return { ok: findings.filter((f) => !SOFT_FINDINGS.has(f.kind)).length === 0, findings };
}

/** Findings that report a limit of this check rather than a defect in a test. */
export const SOFT_FINDINGS = new Set(["no-tests", "unstubbable", "unsupported-language"]);

/** Copy the working tree (minus git, worktrees, node_modules) into a scratch dir. */
export function copyRepo(root, dest, cfg) {
  const skip = new Set([".git", "node_modules", cfg.paths.worktrees.replace("./", ""), cfg.paths.state.replace("./", "")]);
  fs.cpSync(root, dest, {
    recursive: true,
    force: true,
    filter: (src) => {
      const rel = norm(path.relative(root, src));
      if (!rel) return true;
      const top = rel.split("/")[0];
      return !skip.has(top);
    },
  });
}
